// vue2/src/App.vue
<template>
    <div class="container">
        <button @click="addItem">添加</button>
        <div class="action-bar">
            <label for="search">
                <input name="search" type="search" placeholder="输入关键字搜索" v-model="keywords" />
            </label>
            <button @click="onFilterDone('done')">已办</button>
            <button @click="onFilterDone('todo')">待办</button>
        </div>
        <ul>
            <template v-for="(item, index) in displayList">
                <todo-item :key="index" :item="item" @edit="editItem" @remove="removeItem" @done="value => onSwitchItem(value, index)"></todo-item>
            </template>
        </ul>
    </div>
</template>

<script>
import TodoItem from "./components/TodoItem.vue";

export default {
    name: "App",
    components: {
        TodoItem
    },
    data() {
        return {
            list: [
                {
                    name: "测试1",
                    checked: false
                },
                {
                    name: "测试2",
                    checked: false
                }
            ],
            count: 1,
            keywords: "",
            filters: {
                status: "none"
            }

        }
    },
    computed: {
        displayList() {
            var list = [];
            var keywords = this.keywords.trim();
            if (keywords) {
                this.list.forEach(item => {
                    if (item.name.indexOf(keywords) > -1) {
                        list.push(item);
                    }
                });
            } else {
                list = this.list;
            }

            list = this.filterList(list);
            return list;
        }
    },
    methods: {
        addItem() {
            this.list.push({
                name: "新增" + this.count,
                checked: false
            });
            this.count += 1;
        },
        removeItem(index) {
            this.list.splice(index, 1);
        },
        editItem(value, index) {
            const item = this.list[index];
            item.name = value;
            this.$set(this.list, index, item);
        },

        onSwitchItem(value, index) {
            const item = this.list[index];
            item.checked = value;
            this.$set(this.list, index, item);
        },

        onFilterDone(type) {
            let status = this.filters.status;
            if (status === type) {
                status = "none";
            } else {
                status = type;
            }
            this.$set(this.filters, "status", status);
        },

        filterList(list) {
            const filters = this.filters;
            const status = filters.status;
            let newList = [];
            newList = list.filter(item => {
                return (
                    (status === "done" && item.checked) ||
                    (status === "todo" && !item.checked) ||
                    status === "none"
                );
            });

            return newList;
        }
    }
};
</script>

<style>
</style>

// react/src/App.js
import React from 'react';
import './App.css';

import TodoItem from './components/todoItem';

class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            list: [{
                name: '测试1',
                checked: false
            }, {
                name: '测试2',
                checked: false
            }],
            count: 1,
            keywords: '',
            filters: {
                status: 'none'
            }
        };
    }

    addItem() {
        const list = this.state.list.slice();
        const count = this.state.count
        list.push({
            name: '新增' + count,
            checked: false
        });
        this.setState({
            count: count + 1,
            list
        })
    }

    removeItem(index) {
        const list = this.state.list.slice();
        list.splice(index, 1);
        this.setState({
            list
        })
    }

    editItem(value, index) {
        const list = this.state.list.slice();
        list[index].name = value;
        this.setState({
            list
        })
    }

    onSwitchItem(value, index) {
        const list = this.state.list.slice();
        list[index].checked = value;
        this.setState({
            list
        })
    }

    onChangeKeywords(keywords) {
        this.setState({
            keywords
        })
    }

    onFilterDone(type) {
        let status = this.state.filters.status;
        if (status === type) {
            status = 'none'
        } else {
            status = type
        }
        this.setState({
            filters: {
                status
            }
        })
    }

    filterList(list) {
        const filters = this.state.filters;
        const status = filters.status;
        let newList = [];
        newList = list.filter(item => {
            return (status === 'done' && item.checked) || (status === 'todo' && !item.checked) || status === 'none';
        })

        return newList;
    }

    render() {
        const keywords = this.state.keywords.trim();
        let list = [];
        if (keywords) {
            this.state.list.forEach(item => {
                if (item.name.indexOf(keywords) > -1) {
                    list.push(item);
                }
            })
        } else {
            list = this.state.list.slice();
        }

        list = this.filterList(list);

        return (
            <div className="container">
                <button onClick={() => this.addItem()}>添加</button>
                <div className="action-bar">
                    <label htmlFor="search">
                        <input name="search" type="search" placeholder="输入关键字搜索" onChange={e => this.onChangeKeywords(e.target.value)} />
                    </label>
                    <button onClick={() => this.onFilterDone('done')}>已办</button>
                    <button onClick={() => this.onFilterDone('todo')}>待办</button>
                </div>
                <ul>
                    {
                        list.map((item, index) => {
                            return (
                                <TodoItem
                                    key={index}
                                    item={item}
                                    removeItem={() => this.removeItem(index)}
                                    editItem={value => this.editItem(value, index)}
                                    onSwitchItem={value => this.onSwitchItem(value, index)}
                                ></TodoItem>
                            )
                        })
                    }
                </ul>
            </div>
        );
    }
}

export default App;
