// vue2/src/components/TodoItem.vue
<template>
    <li>
        <input type="checkbox" :checked="item.checked" @input="onSwitchItem" />
        {{item.name}}
        <button @click="onRemoveItem">移除</button>
        <input type="text" :value="item.name" @input="onEditItem" />
    </li>
</template>

<script>
export default {
  name: 'TodoItem',
  props: {
    item: Object
  },
  methods: {
      onSwitchItem(e) {
          this.$emit('done', e.target.checked);
      },

      onEditItem(e) {
          this.$emit('eidt', e.target.value);
      },

      onRemoveItem() {
          this.$emit('remove');
      },
  }

}
</script>

<style>
</style>

// taro/src/pages/index/components/todoItem.tsx
import Nerv, { Component } from 'nervjs'

class TodoItem extends Component {

    render() {
        return (
            <li>
                <input type='checkbox' checked={this.props.item.checked} onChange={e => this.props.onSwitchItem(e.target.checked)} />
                {this.props.item.name}
                <button onClick={() => this.props.removeItem()}>移除</button>
                <input type='text' value={this.props.item.name} onChange={e => this.props.editItem(e.target.value)} />
            </li>
        );
    }
}

export default TodoItem;
